name: Cargo Build & Test

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y gcc-mingw-w64-x86-64-win32
      - run: rustup update stable && rustup default stable
      - run: rustup target add x86_64-pc-windows-gnu
      - run: cargo build --target x86_64-pc-windows-gnu --all-targets --all-features
      - run: cargo test --target x86_64-pc-windows-gnu --all-targets --all-features