name: Cargo Build & Test

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    name: Build and test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          rustup update nightly
          rustup update stable
          rustup default stable
      - run: cargo build -p arxan-disabler -p arxan-disabler-dll --all-features
      - run: cargo test --all-features
      - run: cargo +nightly build -p launcher --all-features