on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Build static library
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup rust
        run: |
          rustup update nightly
          rustup component add rust-src --toolchain nightly
          rustup default nightly
      - name: Create dist foler
        run: |
          mkdir ffi-dist
          mkdir ffi-dist/lib
          cp -R ./include ./ffi-dist
      - name: Build with ffi,disabler
        run: |
          ./scripts/build-staticlib-min.bat -F disabler,ffi
          mv ./target/release/arxan_disabler.lib ./ffi-dist/lib/arxan_disabler_lib
      - name: Build with ffi,disabler-debug
        run: |
          ./scripts/build-staticlib-min.bat -F disabler-debug,ffi
          mv ./target/release/arxan_disabler.lib ./ffi-dist/lib/arxan_disabler_debug.lib
      - name: crates.io publish
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
      - name: Zip release
        run: Compress-Archive -Path ./ffi-dist -DestinationPath "arxan-disabler-${{ github.ref_name }}.zip"
      - name: GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: arxan-disabler-${{ github.ref_name }}.zip